spring:
  datasource:
    username: root 
    password: PASSWORD
    url: jdbc:mysql://localhost:3306/REPORTS_API
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true    
    
    