spring:
 datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: PASSWORD
    url: jdbc:mysql://localhost:3306/PLANS_API
    username: root
 jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

        
        
plan-api:
 messages:
  planSaveSucc: Plan Saved Successfully
  planSaveFail: Plan Save Failed
  planUpdateSucc: Plan Updated Successfully
  planUpdateFail: Plan Update Failed
  planDeleteSucc: Plan Deleted Successfully
  planDeleteFail: Plan Delete Failed
  planStatusChange: Plan Status Changed Successfully
  planStatusChangeFail: Plan Status Change Failed
